### PR TITLE
Check for invalid characters

### LINKED ISSUE #171: Smidge should do some validation before processing/writing a file
Example:

```
System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'C:\Website\data\Smidge\Cache\U\sw7pscd7ms4e'||''
at System.IO.FileSystem.CreateDirectory(System.String fullPath, System.Byte[] securityDescriptor)
at System.IO.Directory.CreateDirectory(System.String path)
at Smidge.Cache.PhysicalFileCacheFileSystem.WriteFileAsync(System.String filePath, System.String contents) at offset 71
at Smidge.FileProcessors.PreProcessManager.<ProcessFileImpl>d__7.MoveNext() at offset 1373
at Smidge.FileProcessors.PreProcessManager.<ProcessFile>d__6.MoveNext() at offset 328
at Smidge.FileProcessors.PreProcessManager.<ProcessAndCacheFileAsync>d__5.MoveNext() at offset 222
at Smidge.Controllers.SmidgeController.<Bundle>d__7.MoveNext() at offset 1360
```

Another example:
```sw7pscd7ms4e%' AND 2*3*8=6*8```

### PR DESCRIPTION
**Pull request by PhyxionNL**
+ Add compression level to bundles.

@Shazwazza This fixes #171 #135

### CODE REVIEW

**Comment by Shazwazza** [comment]
Which version/branch did you want to target for this PR? I'm just doing a review and there seems to be some changes that are already done which makes me think that you don't want to target the `master` branch?

**Comment by PhyxionNL** [comment]
It's based on the latest commit in master branch.

File: src/Smidge/Controllers/CompositeFileCacheFilterAttribute.cs [hunk 1]
```diff
@@ -28,7 +28,7 @@ public IFilterMetadata CreateInstance(IServiceProvider serviceProvider)
         internal static bool TryGetCachedCompositeFileResult(ISmidgeFileSystem fileSystem, string cacheBusterValue, string filesetKey, CompressionType type, string mime, out FileResult result, out DateTime lastWriteTime)
         {
             result = null;
-            lastWriteTime = DateTime.Now;
+            lastWriteTime = DateTime.MinValue;
```
Comment (Shazwazza) [inline src/Smidge/Controllers/CompositeFileCacheFilterAttribute.cs:31]: This is a functional change - is this fixing another issue?

File: src/Smidge/Controllers/SmidgeController.cs [hunk 2]
```diff
@@ -192,7 +192,7 @@ public class SmidgeController : Controller
 
                 using (var resultStream = await GetCombinedStreamAsync(files, bundleContext))
                 {
-                    var compressedStream = await Compressor.CompressAsync(file.Compression, resultStream);
+                    var compressedStream = await Compressor.CompressAsync(file.Compression, CompressionLevel.Optimal, resultStream);
```
Comment (Shazwazza) [inline src/Smidge/Controllers/SmidgeController.cs:195]: This is a functional change, is this fixing anotehr issue?

File: src/Smidge.Core/Options/BundleOptions.cs [hunk 3]
```diff
@@ -80,6 +81,11 @@ public Type GetCacheBusterType()
         /// </summary>
         public bool CompressResult { get; set; }
 
+        /// <summary>
+        /// The compression level of the bundle
+        /// </summary>
+        public CompressionLevel CompressionLevel {get; set; }
```
Comment (Shazwazza) [inline src/Smidge.Core/Options/BundleOptions.cs:87]: Is this addressing another issue/feature?

File: src/Smidge.Core/CompositeFiles/Compressor.cs [hunk 4]
```diff
@@ -11,23 +11,23 @@ namespace Smidge.CompositeFiles
     /// </summary>
     public static class Compressor
     {        
-        public static async Task<Stream> CompressAsync(CompressionType type, Stream original)
+        public static async Task<Stream> CompressAsync(CompressionType type, CompressionLevel level, Stream original)
```
[the remark this answers is not in the document]
Comment (PhyxionNL) [reply src/Smidge.Core/CompositeFiles/Compressor.cs:14]: Yes, I'll change this.

File: src/Smidge.Core/CompositeFiles/DefaultUrlManager.cs [hunk 5]
```diff
@@ -137,23 +134,25 @@ public ParsedUrlPath ParsePath(string input)
...
             if (prefix != 'v' && prefix != 'd')
             {
                 //invalid
                 return null;
             }
             result.Debug = prefix == 'd';
-
-            result.CacheBusterValue = _config.KeepFileExtensions ? parts[parts.Length - 2].Substring(1) : parts[parts.Length - 1].Substring(1);
-            var ext = _config.KeepFileExtensions ? parts[parts.Length - 1] : parts[parts.Length - 2];
-            if (!Enum.TryParse(ext, true, out WebFileType type))
```
[the remark this answers is not in the document]
Comment (PhyxionNL) [reply src/Smidge.Core/CompositeFiles/DefaultUrlManager.cs:150]: Nothing wrong as such, but Enum.TryParse is much slower than this, and there are only two values to check here.

File: src/Smidge/Controllers/CompositeFileCacheFilterAttribute.cs (hunk 1 above)
Comment (PhyxionNL) [reply src/Smidge/Controllers/CompositeFileCacheFilterAttribute.cs:31]: This was meant to be moved to the bottom, updated.

File: src/Smidge/Controllers/SmidgeController.cs (hunk 2 above)
Comment (PhyxionNL) [reply src/Smidge/Controllers/SmidgeController.cs]: See below.

File: src/Smidge.Core/Options/BundleOptions.cs (hunk 3 above)
Comment (PhyxionNL) [reply src/Smidge.Core/Options/BundleOptions.cs:87]: Yes, I have added this as Smidge was hardcoding this to Optimal. This setting is usually preferred, but I'd like this configurable for bundles so I can use Fastest for local testing.

Comment (Shazwazza) [reply src/Smidge.Core/Options/BundleOptions.cs:87]: Okidoke, IIRC I think there is a ticket on the tracker for this which may be able to be resolved then.

Comment (PhyxionNL) [reply src/Smidge.Core/Options/BundleOptions.cs:87]: #135 should be that, I'll add that to description so it can be closed.

File: src/Smidge.Core/CompositeFiles/DefaultUrlManager.cs (hunk 5 above)
[the remark this answers is not in the document]
Comment (Shazwazza) [reply src/Smidge.Core/CompositeFiles/DefaultUrlManager.cs:150]: ok

File: src/Smidge/Models/RequestModel.cs [hunk 6]
```diff
@@ -17,7 +17,7 @@ protected RequestModel(string valueName, IUrlManager urlManager, IActionContextA
             if (requestHelper is null)throw new ArgumentNullException(nameof(requestHelper));
 
             //default 
-            LastFileWriteTime = DateTime.Now;
+            LastFileWriteTime = DateTime.MinValue;
```
Comment (Shazwazza) [inline src/Smidge/Models/RequestModel.cs:20]: I thought I asked about this before but can't find the convo. What is this change addressing?

Comment (PhyxionNL) [reply src/Smidge/Models/RequestModel.cs:20]: This default is updated here to the right one: https://github.com/Shazwazza/Smidge/blob/b0383c3b7e2b667402451dcff7055209ceabd428/src/Smidge/Controllers/CompositeFileCacheFilterAttribute.cs#L36
DateTime.MinValue doesn't do anything whereas DateTime.Now retrieves the date/time and timezone information etc.

**Review by Shazwazza — APPROVED** [review]
